// 백엔드 API 응답 형태. 기준 스펙은 docs/openapi.yaml, 미해결 논의점은 docs/openapi-1차-대비-변경점.md §5.
//
// 병합은 githubUrl·imageUrl만 덮어써요. role·affiliation·cohorts·tracks·history·intro는 큐레이션 유지 —
// 백엔드 enum이 회장·영입리드 같은 직함과 기수별 트랙 이력(2기 FE → 3기 BE)을 아직 표현 못 해서예요.

export type MemberStackPosition = "BACKEND" | "FRONTEND" | "FULL_STACK";
export type MemberActivityType = "CO_FOUNDER" | "MAINTAINER" | "STUDY_LEAD" | "STUDY_MEMBER" | "REVIEWER";
export type MemberDepartment = "COMPUTER_SCIENCE" | "SOFTWARE" | "INFO_COMMUNICATION" | "AI" | "ETC";

export type MemberActivityDto = {
  activityType: MemberActivityType;
  generationNumber: number | null;
};

export type MemberDto = {
  id: number;
  name: string;
  githubUrl: string | null;
  imageUrl: string | null;
  mainStackPosition: MemberStackPosition;
  departments: MemberDepartment[];
  memberActivities: MemberActivityDto[];
};

/** MSW 목서버 픽스처. 실제 그리디 46명 명단(노션 "그리디 멤버 최종 정리")을 MemberDto 형태로 옮긴 데이터예요. */
export const MEMBER_DTOS: MemberDto[] = [
  {
    id: 1,
    name: "이승용",
    githubUrl: "https://github.com/kokodak",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "CO_FOUNDER", generationNumber: null },
      { activityType: "MAINTAINER", generationNumber: 1 },
      { activityType: "STUDY_LEAD", generationNumber: 1 },
      { activityType: "REVIEWER", generationNumber: 1 },
      { activityType: "MAINTAINER", generationNumber: 2 },
      { activityType: "STUDY_LEAD", generationNumber: 2 },
      { activityType: "REVIEWER", generationNumber: 2 },
      { activityType: "MAINTAINER", generationNumber: 3 },
    ],
  },
  {
    id: 2,
    name: "원태연",
    githubUrl: "https://github.com/TaeyeonRoyce",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["ETC"],
    memberActivities: [
      { activityType: "CO_FOUNDER", generationNumber: null },
      { activityType: "MAINTAINER", generationNumber: 1 },
      { activityType: "STUDY_LEAD", generationNumber: 1 },
      { activityType: "REVIEWER", generationNumber: 1 },
      { activityType: "MAINTAINER", generationNumber: 2 },
      { activityType: "REVIEWER", generationNumber: 2 },
    ],
  },
  {
    id: 3,
    name: "김수민",
    githubUrl: "https://github.com/boyekim",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "CO_FOUNDER", generationNumber: null },
      { activityType: "MAINTAINER", generationNumber: 1 },
      { activityType: "MAINTAINER", generationNumber: 2 },
      { activityType: "MAINTAINER", generationNumber: 3 },
      { activityType: "REVIEWER", generationNumber: 4 },
    ],
  },
  {
    id: 4,
    name: "김범수",
    githubUrl: "https://github.com/Indigochi1d",
    imageUrl: null,
    mainStackPosition: "FRONTEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "CO_FOUNDER", generationNumber: null },
      { activityType: "MAINTAINER", generationNumber: 1 },
      { activityType: "STUDY_LEAD", generationNumber: 1 },
      { activityType: "REVIEWER", generationNumber: 1 },
      { activityType: "MAINTAINER", generationNumber: 2 },
      { activityType: "STUDY_LEAD", generationNumber: 2 },
      { activityType: "REVIEWER", generationNumber: 2 },
      { activityType: "REVIEWER", generationNumber: 3 },
      { activityType: "MAINTAINER", generationNumber: 4 },
      { activityType: "STUDY_LEAD", generationNumber: 4 },
      { activityType: "REVIEWER", generationNumber: 4 },
    ],
  },
  {
    id: 5,
    name: "김주환",
    githubUrl: "https://github.com/3Juhwan",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "CO_FOUNDER", generationNumber: null },
      { activityType: "MAINTAINER", generationNumber: 1 },
      { activityType: "STUDY_LEAD", generationNumber: 1 },
      { activityType: "REVIEWER", generationNumber: 1 },
      { activityType: "MAINTAINER", generationNumber: 2 },
      { activityType: "STUDY_LEAD", generationNumber: 2 },
    ],
  },
  {
    id: 6,
    name: "송혜정",
    githubUrl: "https://github.com/Songhyejeong",
    imageUrl: null,
    mainStackPosition: "FRONTEND",
    departments: ["ETC"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 1 },
      { activityType: "MAINTAINER", generationNumber: 2 },
      { activityType: "STUDY_LEAD", generationNumber: 2 },
      { activityType: "REVIEWER", generationNumber: 2 },
      { activityType: "MAINTAINER", generationNumber: 3 },
      { activityType: "STUDY_LEAD", generationNumber: 3 },
      { activityType: "REVIEWER", generationNumber: 3 },
      { activityType: "REVIEWER", generationNumber: 4 },
    ],
  },
  {
    id: 7,
    name: "김준수",
    githubUrl: "https://github.com/gogo1414",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["ETC"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 1 },
      { activityType: "MAINTAINER", generationNumber: 3 },
      { activityType: "REVIEWER", generationNumber: 3 },
    ],
  },
  {
    id: 8,
    name: "신혜빈",
    githubUrl: "https://github.com/c0mpuTurtle",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 1 },
      { activityType: "STUDY_LEAD", generationNumber: 3 },
      { activityType: "REVIEWER", generationNumber: 3 },
      { activityType: "MAINTAINER", generationNumber: 4 },
      { activityType: "REVIEWER", generationNumber: 4 },
    ],
  },
  {
    id: 9,
    name: "안금서",
    githubUrl: "https://github.com/goldm0ng",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["SOFTWARE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 1 },
      { activityType: "STUDY_LEAD", generationNumber: 2 },
      { activityType: "STUDY_LEAD", generationNumber: 3 },
    ],
  },
  {
    id: 10,
    name: "정상희",
    githubUrl: "https://github.com/SANGHEEJEONG",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 1 },
      { activityType: "STUDY_LEAD", generationNumber: 2 },
      { activityType: "STUDY_LEAD", generationNumber: 3 },
      { activityType: "REVIEWER", generationNumber: 3 },
      { activityType: "MAINTAINER", generationNumber: 4 },
      { activityType: "STUDY_LEAD", generationNumber: 4 },
    ],
  },
  {
    id: 11,
    name: "남해윤",
    githubUrl: "https://github.com/haeyoon1",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["ETC"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 1 },
      { activityType: "MAINTAINER", generationNumber: 3 },
      { activityType: "STUDY_LEAD", generationNumber: 3 },
      { activityType: "REVIEWER", generationNumber: 3 },
      { activityType: "REVIEWER", generationNumber: 4 },
    ],
  },
  {
    id: 12,
    name: "황승준",
    githubUrl: "https://github.com/davidolleh",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 1 },
    ],
  },
  {
    id: 13,
    name: "신지훈",
    githubUrl: "https://github.com/developowl",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["INFO_COMMUNICATION"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 1 },
      { activityType: "STUDY_MEMBER", generationNumber: 2 },
      { activityType: "MAINTAINER", generationNumber: 3 },
      { activityType: "REVIEWER", generationNumber: 3 },
    ],
  },
  {
    id: 14,
    name: "김의진",
    githubUrl: "https://github.com/sansan20535",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 1 },
    ],
  },
  {
    id: 15,
    name: "신지우",
    githubUrl: "https://github.com/zldn109",
    imageUrl: null,
    mainStackPosition: "FRONTEND",
    departments: ["SOFTWARE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 2 },
      { activityType: "STUDY_LEAD", generationNumber: 3 },
    ],
  },
  {
    id: 16,
    name: "정창우",
    githubUrl: "https://github.com/ChangwooJ",
    imageUrl: null,
    mainStackPosition: "FRONTEND",
    departments: ["INFO_COMMUNICATION"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 2 },
      { activityType: "MAINTAINER", generationNumber: 4 },
      { activityType: "STUDY_LEAD", generationNumber: 4 },
      { activityType: "REVIEWER", generationNumber: 4 },
    ],
  },
  {
    id: 17,
    name: "임규영",
    githubUrl: "https://github.com/gxuoo",
    imageUrl: null,
    mainStackPosition: "FRONTEND",
    departments: ["SOFTWARE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 2 },
      { activityType: "STUDY_LEAD", generationNumber: 3 },
      { activityType: "REVIEWER", generationNumber: 4 },
    ],
  },
  {
    id: 18,
    name: "강동현",
    githubUrl: "https://github.com/mintcoke123",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 2 },
      { activityType: "STUDY_MEMBER", generationNumber: 3 },
    ],
  },
  {
    id: 19,
    name: "박찬빈",
    githubUrl: "https://github.com/INSANE-P",
    imageUrl: null,
    mainStackPosition: "FRONTEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 2 },
      { activityType: "STUDY_LEAD", generationNumber: 3 },
      { activityType: "MAINTAINER", generationNumber: 4 },
      { activityType: "STUDY_LEAD", generationNumber: 4 },
      { activityType: "REVIEWER", generationNumber: 4 },
    ],
  },
  {
    id: 20,
    name: "황혜림",
    githubUrl: "https://github.com/HyerimH",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 2 },
      { activityType: "MAINTAINER", generationNumber: 4 },
    ],
  },
  {
    id: 21,
    name: "허석준",
    githubUrl: "https://github.com/gjtjrl303",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 2 },
    ],
  },
  {
    id: 22,
    name: "전서희",
    githubUrl: "https://github.com/jeonseohee9",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["SOFTWARE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 2 },
    ],
  },
  {
    id: 23,
    name: "이창희",
    githubUrl: "https://github.com/chxghee",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 2 },
      { activityType: "REVIEWER", generationNumber: 4 },
    ],
  },
  {
    id: 24,
    name: "김지우",
    githubUrl: "https://github.com/Ji-Woo-Kim",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 2 },
    ],
  },
  {
    id: 25,
    name: "염지환",
    githubUrl: "https://github.com/JihwanYeom",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["SOFTWARE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 2 },
    ],
  },
  {
    id: 26,
    name: "윤재홍",
    githubUrl: "https://github.com/yoonjaehong26",
    imageUrl: null,
    mainStackPosition: "FRONTEND",
    departments: ["SOFTWARE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 3 },
      { activityType: "MAINTAINER", generationNumber: 4 },
      { activityType: "STUDY_LEAD", generationNumber: 4 },
    ],
  },
  {
    id: 27,
    name: "심혁",
    githubUrl: "https://github.com/johncakes",
    imageUrl: null,
    mainStackPosition: "FRONTEND",
    departments: ["SOFTWARE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 3 },
      { activityType: "MAINTAINER", generationNumber: 4 },
      { activityType: "STUDY_LEAD", generationNumber: 4 },
    ],
  },
  {
    id: 28,
    name: "강건",
    githubUrl: "https://github.com/dkr-sjr",
    imageUrl: null,
    mainStackPosition: "FRONTEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 3 },
    ],
  },
  {
    id: 29,
    name: "강예령",
    githubUrl: "https://github.com/ehlung",
    imageUrl: null,
    mainStackPosition: "FRONTEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 3 },
    ],
  },
  {
    id: 30,
    name: "이고은",
    githubUrl: "https://github.com/ke-62",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 3 },
    ],
  },
  {
    id: 31,
    name: "하수한",
    githubUrl: "https://github.com/chemistryx",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["SOFTWARE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 3 },
      { activityType: "REVIEWER", generationNumber: 4 },
    ],
  },
  {
    id: 32,
    name: "김태우",
    githubUrl: "https://github.com/tae-wooo",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["SOFTWARE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 3 },
    ],
  },
  {
    id: 33,
    name: "서현진",
    githubUrl: "https://github.com/nonactress",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 3 },
    ],
  },
  {
    id: 34,
    name: "김하늘",
    githubUrl: "https://github.com/kimsky247-coder",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["INFO_COMMUNICATION"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 3 },
    ],
  },
  {
    id: 35,
    name: "김민기",
    githubUrl: "https://github.com/supernovaMK",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["SOFTWARE"],
    memberActivities: [
      { activityType: "MAINTAINER", generationNumber: 4 },
      { activityType: "REVIEWER", generationNumber: 4 },
    ],
  },
  {
    id: 36,
    name: "이진",
    githubUrl: "https://github.com/2Jin1031",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["ETC", "COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "MAINTAINER", generationNumber: 4 },
      { activityType: "REVIEWER", generationNumber: 4 },
    ],
  },
  {
    id: 37,
    name: "홍의민",
    githubUrl: "https://github.com/EM-H20",
    imageUrl: null,
    mainStackPosition: "FRONTEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 4 },
    ],
  },
  {
    id: 38,
    name: "김동건",
    githubUrl: "https://github.com/rahwan10",
    imageUrl: null,
    mainStackPosition: "FRONTEND",
    departments: ["ETC"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 4 },
    ],
  },
  {
    id: 39,
    name: "고규민",
    githubUrl: "https://github.com/kokunut",
    imageUrl: null,
    mainStackPosition: "FRONTEND",
    departments: ["ETC"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 4 },
    ],
  },
  {
    id: 40,
    name: "천동현",
    githubUrl: "https://github.com/realcdh",
    imageUrl: null,
    mainStackPosition: "FRONTEND",
    departments: ["ETC"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 4 },
    ],
  },
  {
    id: 41,
    name: "김민욱",
    githubUrl: "https://github.com/hapdaypy",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 4 },
    ],
  },
  {
    id: 42,
    name: "강대현",
    githubUrl: "https://github.com/Kdahyn",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["ETC"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 4 },
    ],
  },
  {
    id: 43,
    name: "정명준",
    githubUrl: "https://github.com/htdufhc-bit",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 4 },
    ],
  },
  {
    id: 44,
    name: "이채현",
    githubUrl: "https://github.com/chaehyunL",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["AI"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 4 },
    ],
  },
  {
    id: 45,
    name: "김하은",
    githubUrl: "https://github.com/haeun92e0",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["ETC", "COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 4 },
    ],
  },
  {
    id: 46,
    name: "이태규",
    githubUrl: "https://github.com/Cappucciyes",
    imageUrl: null,
    mainStackPosition: "BACKEND",
    departments: ["COMPUTER_SCIENCE"],
    memberActivities: [
      { activityType: "STUDY_MEMBER", generationNumber: 4 },
    ],
  },
];
